services:
  nginx:
    build: .
    ports:
      - "3333:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - /data/files:/files
      - /data/nginx-images-cache:/nginx-images-cache
    env_file:
      - .env
